### ISSUE TITLE
get plot data

### ISSUE THREAD

**Issue by d7coders** [e2nIEE/pandapower#1603] opened 2022-06-03 22:32 UTC
how to get pf_res_plotly data instead of a HTML file?
the HTML file contains plotly js file which is big ( about 3.7 MB)
I can load the plotly.js file in the front end side so the browser cache it for the next time
and just transfer the data to draw the plot

**Comment by jkisse** [comment] 2022-06-10 09:11
Closing this, because this is issue is a duplicate of #1589

**Closed by jkisse** 2022-06-10 09:11 UTC
