### ISSUE TITLE
OPF tutorial not converging with constraint parameters

### ISSUE THREAD

**Issue by Hericles-Farias** [e2nIEE/pandapower#748] opened 2020-04-17 05:07 UTC
Hi, I can't perform the simulation of the pandapower Optimal Power Flow, from the tutorials, whenever I use the "net.trafo["max_loading_percent"] = 50", or the line restriction, I get the Not Converging OPF message, but without this line of code it works. I was using the pandapower 2.2.2, that I had installed via pip, then I changed to the version to 2.1.0, and in this specific version it also worked with the restrictio parameter.  What could I do to solve this issue in the 2.2.2 version?

**Comment by Damowerko** [comment] 2020-05-05 17:09
This issue is a duplicate of #733

**Comment by TravisCao** [comment] 2020-08-17 14:17
So is there any idea about solving this problem by now? @Damowerko

**Comment by inratkaisija** [comment] 2020-08-24 12:41
@Hericles-Farias Thanks for reporting this problem. Indeed, from version 2.1.0 to 2.2.0 the OPF bounds and settings for generators were changed. From version 2.2.0 on, limits or fixed values can be enforced. To make sure that the OPF converges, you can set the power tolerance to `delta=1e-16` and give it as an input to `runopp()`. Also see the updated tutorial.

**Closed** 2020-08-24 13:01 UTC
Labels: OPF
