### ISSUE TITLE
DepreciationWarning: ipragh --> jgraph error in /pandapower/plotting/generic_geodata.py

### ISSUE THREAD

**Issue by JoachimSchaeffer** [e2nIEE/pandapower#941] opened 2020-10-06 10:22 UTC
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

Should be easy to fix. Let me know whether there are any questions. 
Many thanks!

<img width="794" alt="Screenshot 2020-10-06 at 12 19 36" src="https://user-images.githubusercontent.com/63883039/95189599-5e332680-07ce-11eb-9fb8-0994e33bd9d9.png">

**Comment by JoachimSchaeffer** [comment] 2020-10-06 10:26
P.S.: Easy fix is pip uninstall igraph. 
(Of course you cannot use igraph functions anymore)
The error occured in the plotting_basic notebook from the powerpandas repo.

**Comment by rbolgaryn** [comment] 2020-11-06 13:46
Hi @JoachimSchaeffer ,

is the errior still occurring with the latest version of igraph?

**Comment by rbolgaryn** [comment] 2020-12-01 14:31
cannot reproduce, haven't gotten any updates, closing the issue

**Closed by rbolgaryn** 2020-12-01 14:31 UTC
Labels: plotting
